[package]
name = "funcperm"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
rand = "0.10.0"
criterion = { version = "0.5", features = ["html_reports"] }
anyhow = "1"

[[bench]]
name = "bench"
harness = false
